/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BulkPriceUpdateInput = IDL.Record({
  'productId' : IDL.Nat,
  'newPrice' : IDL.Float64,
});
export const ProductCategory = IDL.Variant({
  'other' : IDL.Null,
  'door' : IDL.Null,
  'gate' : IDL.Null,
  'window' : IDL.Null,
});
export const CreateProductInput = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : ProductCategory,
  'price' : IDL.Float64,
});
export const ProductId = IDL.Nat;
export const PriceRecord = IDL.Record({
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'isAvailable' : IDL.Bool,
  'priceHistory' : IDL.Vec(PriceRecord),
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : ProductCategory,
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactInfo = IDL.Record({
  'mapLink' : IDL.Text,
  'email' : IDL.Text,
  'workingHours' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdateProductInput = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'unit' : IDL.Opt(IDL.Text),
  'isAvailable' : IDL.Opt(IDL.Bool),
  'description' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(ProductCategory),
  'price' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpdatePrices' : IDL.Func([IDL.Vec(BulkPriceUpdateInput)], [], []),
  'createProduct' : IDL.Func([CreateProductInput], [ProductId], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductPriceHistory' : IDL.Func(
      [ProductId],
      [IDL.Vec(PriceRecord)],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateContactInfo' : IDL.Func([ContactInfo], [], []),
  'updateProduct' : IDL.Func([ProductId, UpdateProductInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BulkPriceUpdateInput = IDL.Record({
    'productId' : IDL.Nat,
    'newPrice' : IDL.Float64,
  });
  const ProductCategory = IDL.Variant({
    'other' : IDL.Null,
    'door' : IDL.Null,
    'gate' : IDL.Null,
    'window' : IDL.Null,
  });
  const CreateProductInput = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : ProductCategory,
    'price' : IDL.Float64,
  });
  const ProductId = IDL.Nat;
  const PriceRecord = IDL.Record({
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'isAvailable' : IDL.Bool,
    'priceHistory' : IDL.Vec(PriceRecord),
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : ProductCategory,
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactInfo = IDL.Record({
    'mapLink' : IDL.Text,
    'email' : IDL.Text,
    'workingHours' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdateProductInput = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'unit' : IDL.Opt(IDL.Text),
    'isAvailable' : IDL.Opt(IDL.Bool),
    'description' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(ProductCategory),
    'price' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpdatePrices' : IDL.Func([IDL.Vec(BulkPriceUpdateInput)], [], []),
    'createProduct' : IDL.Func([CreateProductInput], [ProductId], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductPriceHistory' : IDL.Func(
        [ProductId],
        [IDL.Vec(PriceRecord)],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateContactInfo' : IDL.Func([ContactInfo], [], []),
    'updateProduct' : IDL.Func([ProductId, UpdateProductInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };