/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BulkPriceUpdateInput {
  'productId' : bigint,
  'newPrice' : number,
}
export interface ContactInfo {
  'mapLink' : string,
  'email' : string,
  'workingHours' : string,
  'address' : string,
  'phone' : string,
}
export interface CreateProductInput {
  'name' : string,
  'unit' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : [] | [string],
  'category' : ProductCategory,
  'price' : number,
}
export interface PriceRecord { 'timestamp' : bigint, 'price' : number }
export interface Product {
  'id' : ProductId,
  'name' : string,
  'unit' : string,
  'lastUpdated' : bigint,
  'isAvailable' : boolean,
  'priceHistory' : Array<PriceRecord>,
  'description' : string,
  'imageUrl' : [] | [string],
  'category' : ProductCategory,
  'price' : number,
}
export type ProductCategory = { 'other' : null } |
  { 'door' : null } |
  { 'gate' : null } |
  { 'window' : null };
export type ProductId = bigint;
export interface UpdateProductInput {
  'name' : [] | [string],
  'unit' : [] | [string],
  'isAvailable' : [] | [boolean],
  'description' : [] | [string],
  'imageUrl' : [] | [string],
  'category' : [] | [ProductCategory],
  'price' : [] | [number],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdatePrices' : ActorMethod<[Array<BulkPriceUpdateInput>], undefined>,
  'createProduct' : ActorMethod<[CreateProductInput], ProductId>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], [] | [ContactInfo]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductPriceHistory' : ActorMethod<[ProductId], Array<PriceRecord>>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'updateProduct' : ActorMethod<[ProductId, UpdateProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];